#!/usr/bin/env python3
"""
SIDBOX applet.ld generator.

Run this from an applet project directory:

    python3 tools/applet_ld_wizard.py

The wizard writes applet.ld only after asking for confirmation. Use --dry-run to
preview the generated linker script without touching anything.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


SDRAM_BASE = 0xD0000000
SDRAM_SIZE = 6 * 1024 * 1024
API_COUNT = 512
STACK_SIZE = 8 * 1024
ALIGNMENT = 32

SIZE_CHOICES = {
    "1": ("16 KB", 16 * 1024),
    "2": ("32 KB", 32 * 1024),
    "3": ("64 KB", 64 * 1024),
    "4": ("128 KB", 128 * 1024),
    "5": ("256 KB", 256 * 1024),
    "6": ("512 KB", 512 * 1024),
    "7": ("1 MB", 1024 * 1024),
}

MUSIC_CHOICES = {
    "1": ("None", 0),
    "2": ("64 KB", 64 * 1024),
    "3": ("128 KB", 128 * 1024),
    "4": ("256 KB", 256 * 1024),
    "5": ("512 KB", 512 * 1024),
    "6": ("1 MB", 1024 * 1024),
    "7": ("2 MB", 2 * 1024 * 1024),
}


@dataclass(frozen=True)
class LinkerConfig:
    profile: str
    app_limit: int
    mod_limit: int
    resource_limit: int

    @property
    def startram(self) -> int:
        if self.profile == "desktop":
            return align_down(SDRAM_SIZE - self.app_limit, ALIGNMENT)
        return align_up(self.mod_limit + self.resource_limit, ALIGNMENT)

    @property
    def app_length(self) -> int:
        return SDRAM_SIZE - self.startram

    @property
    def app_origin(self) -> int:
        return SDRAM_BASE + self.startram


def align_up(value: int, alignment: int) -> int:
    return (value + alignment - 1) & ~(alignment - 1)


def align_down(value: int, alignment: int) -> int:
    return value & ~(alignment - 1)


def format_bytes(value: int) -> str:
    if value == 0:
        return "0 bytes"
    if value % (1024 * 1024) == 0:
        return f"{value // (1024 * 1024)} MB"
    if value % 1024 == 0:
        return f"{value // 1024} KB"
    return f"{value} bytes"


def parse_size(text: str) -> int:
    value = text.strip().lower().replace(" ", "")
    multipliers = {
        "k": 1024,
        "kb": 1024,
        "m": 1024 * 1024,
        "mb": 1024 * 1024,
        "b": 1,
    }

    for suffix, multiplier in sorted(multipliers.items(), key=lambda item: -len(item[0])):
        if value.endswith(suffix):
            number = value[: -len(suffix)]
            break
    else:
        number = value
        multiplier = 1024

    if not number.isdigit():
        raise ValueError(f"Could not parse size: {text!r}")

    parsed = int(number) * multiplier
    if parsed < 0:
        raise ValueError("Size cannot be negative")
    return parsed


def ask_yes_no(question: str, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        answer = input(f"{question} {suffix} ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("Please answer y or n.")


def ask_choice(question: str, choices: dict[str, tuple[str, int]], default: str) -> int:
    print(question)
    for key, (label, bytes_value) in choices.items():
        print(f"  {key}. {label:<6} ({bytes_value:#x})")
    print("  c. Custom")

    while True:
        answer = input(f"Choice [{default}]: ").strip().lower() or default
        if answer in choices:
            return choices[answer][1]
        if answer == "c":
            return ask_size("Enter custom size, e.g. 96KB or 2MB")
        print("Pick one of the listed choices.")


def ask_size(question: str) -> int:
    while True:
        answer = input(f"{question}: ").strip()
        try:
            return parse_size(answer)
        except ValueError as error:
            print(error)


def validate_config(config: LinkerConfig) -> list[str]:
    errors: list[str] = []
    if config.app_limit <= 0:
        errors.append("App size must be greater than zero.")
    if config.resource_limit < 0 or config.mod_limit < 0:
        errors.append("Reserved sizes cannot be negative.")
    if config.startram >= SDRAM_SIZE:
        errors.append("Reserved music/resource space leaves no SDRAM for the applet.")
    if config.app_length <= STACK_SIZE + 0x1000:
        errors.append(
            "App allowance is very small after the stack reserve. Pick a larger app size."
        )
    if config.profile == "game" and config.app_length < config.app_limit:
        errors.append(
            "Music/resource reserves leave less space than the app size you selected."
        )
    return errors


def render_linker_script(config: LinkerConfig) -> str:
    return f"""/*
    applet.ld - generated by tools/applet_ld_wizard.py

    Profile: {config.profile}
    SDRAM base: 0x{SDRAM_BASE:08X}
    Usable SDRAM: {format_bytes(SDRAM_SIZE)} / 0x{SDRAM_SIZE:X}
    Reserved before applet: {format_bytes(config.startram)} / 0x{config.startram:X}
    Applet origin: 0x{config.app_origin:08X}
    Applet allowance: {format_bytes(config.app_length)} / 0x{config.app_length:X}
*/

/* Base and limits */
_offset            = 0x{SDRAM_BASE:08X};
_maxramavail       = 0x{SDRAM_SIZE:X};
_stack_size        = 0x{STACK_SIZE:X};

/* Wizard choices, all in bytes. Do not multiply these by 1024 again. :) */
_profile_is_desktop = {1 if config.profile == "desktop" else 0};
_requested_app_size = 0x{config.app_limit:X};
_largest_modfile    = 0x{config.mod_limit:X};
_largest_resource   = 0x{config.resource_limit:X};

/* Desktop apps are parked near the end of SDRAM.
   Games start after the reserved music/resource area. */
_desktop_startram = ((_maxramavail - _requested_app_size) & ~31);
_game_startram    = ((_largest_modfile + _largest_resource + 31) & ~31);
_startram         = _profile_is_desktop ? _desktop_startram : _game_startram;

_applet_origin    = _offset + _startram;
_applet_length    = _maxramavail - _startram;
_sdram_end        = _offset + _maxramavail;

ASSERT(_startram < _maxramavail, "Reserved space exceeds SDRAM size!")
ASSERT(_applet_length > _stack_size, "No RAM left for applet after stack reserve!")
ASSERT((_startram & 31) == 0, "Applet start must be 32-byte aligned!")

/* SIDBOX API table location. Must match the core applets linker layout. */
_api_count = {API_COUNT};
_api_size  = (8 * _api_count);
_api_location = 0x20020000 - _api_size;

MEMORY {{
    APPLET (rwx) : ORIGIN = (_offset + _startram), LENGTH = (_maxramavail - _startram)
}}

_appstart = ORIGIN(APPLET);
PROVIDE(__app_start = _appstart);

SECTIONS {{
    PROVIDE(__sidbox_api_location = _api_location);

    . = _appstart;

    /* Header = 16 bytes total: magic(8) + loadAddr(4) + memLen(4) */
    .header _appstart : {{
        . = ALIGN(4);
        KEEP(*(.header))
        . = ALIGN(4);
        LONG(_appstart);
        LONG(__stack_end__ - _appstart);
    }} > APPLET

    .text (_appstart + 0x10) : {{
        . = ALIGN(4);
        KEEP(*(.text.applet_entry))
        *(.text*)
        *(.rodata*)
    }} > APPLET

    .data : {{
        . = ALIGN(4);
        *(.data*)
    }} > APPLET

    .bss (NOLOAD) : {{
        . = ALIGN(4);
        __bss_start__ = .;
        *(.bss*)
        *(COMMON)
        . = ALIGN(4);
        __bss_end__ = .;
    }} > APPLET

    .stack (NOLOAD) : {{
        . = ALIGN(8);
        __stack_start__ = .;
        . = . + _stack_size;
        . = ALIGN(8);
        __stack_end__ = .;
    }} > APPLET

    PROVIDE(__app_end_clear = __stack_end__);
    PROVIDE(_estack = __stack_end__);

    _end = .;
    __app_end = .;

    ASSERT(__stack_end__ <= (_appstart + LENGTH(APPLET)), "Applet image exceeds selected app size!")
    ASSERT(__stack_end__ <= _sdram_end, "Applet image exceeds SDRAM end!")
}}
"""


def run_wizard() -> LinkerConfig:
    print("SIDBOX applet.ld wizard")
    print("=======================")
    print(f"Usable SDRAM: {format_bytes(SDRAM_SIZE)} / 0x{SDRAM_SIZE:X}")
    print()

    is_desktop = ask_yes_no("Is this a desktop/environment app?", default=True)
    profile = "desktop" if is_desktop else "game"

    if is_desktop:
        app_limit = ask_choice(
            "How much RAM should the applet itself be allowed?",
            SIZE_CHOICES,
            default="3",
        )
        mod_limit = SDRAM_SIZE - app_limit
    else:
        mod_limit = ask_choice(
            "How much space should be reserved for music/MOD data?",
            MUSIC_CHOICES,
            default="4",
        )
        app_limit = SDRAM_SIZE - mod_limit

    resource_limit = ask_size("Resource reserve in KB/MB, or 0") if ask_yes_no(
        "Reserve extra resource space before the applet?", default=False
    ) else 0

    if resource_limit >= SDRAM_SIZE:
        print("Resource reserve consumes all SDRAM. That is a bold strategy. Also no.")
        raise SystemExit(1)

    if is_desktop:
        app_limit = min(app_limit, SDRAM_SIZE - resource_limit)
        mod_limit = SDRAM_SIZE - app_limit - resource_limit

    config = LinkerConfig(
        profile=profile,
        app_limit=app_limit,
        mod_limit=mod_limit,
        resource_limit=resource_limit,
    )

    errors = validate_config(config)
    if errors:
        print()
        print("That layout does not fit:")
        for error in errors:
            print(f"  - {error}")
        raise SystemExit(1)

    print()
    print("Planned layout")
    print("--------------")
    print(f"Profile:          {config.profile}")
    print(f"Applet origin:    0x{config.app_origin:08X}")
    print(f"Applet allowance: {format_bytes(config.app_length)} / 0x{config.app_length:X}")
    print(f"Reserved before:  {format_bytes(config.startram)} / 0x{config.startram:X}")
    print(f"Music reserve:    {format_bytes(config.mod_limit)} / 0x{config.mod_limit:X}")
    print(f"Resource reserve: {format_bytes(config.resource_limit)} / 0x{config.resource_limit:X}")
    print()

    return config


def write_output(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        if not ask_yes_no(f"{path} already exists. Overwrite it?", default=False):
            print("Cancelled. No files changed.")
            return
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a SIDBOX applet.ld file.")
    parser.add_argument("-o", "--output", default="applet.ld", help="Output linker script path")
    parser.add_argument("--dry-run", action="store_true", help="Print the script instead of writing it")
    parser.add_argument("--force", action="store_true", help="Overwrite output without prompting")
    args = parser.parse_args()

    config = run_wizard()
    script = render_linker_script(config)

    if args.dry_run:
        print(script)
        return

    write_output(Path(args.output), script, args.force)


if __name__ == "__main__":
    main()
